[2025-04-18T00:35:08.568+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T00:35:08.641+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:35:07.408100+00:00 [queued]>
[2025-04-18T00:35:08.655+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:35:07.408100+00:00 [queued]>
[2025-04-18T00:35:08.657+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T00:35:08.675+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_order_items> on 2025-04-18 00:35:07.408100+00:00
[2025-04-18T00:35:08.684+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_order_items', 'load_new_order_items', 'manual__2025-04-18T00:35:07.408100+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_order_items.py', '--cfg-path', '/tmp/tmp9o63d19c']
[2025-04-18T00:35:08.687+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=908) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T00:35:08.689+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask load_new_order_items
[2025-04-18T00:35:08.689+0000] {standard_task_runner.py:72} INFO - Started process 909 to run task
[2025-04-18T00:35:08.884+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:35:07.408100+00:00 [running]> on host f693ba064550
[2025-04-18T00:35:09.151+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_order_items' AIRFLOW_CTX_TASK_ID='load_new_order_items' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:35:07.408100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T00:35:07.408100+00:00'
[2025-04-18T00:35:09.152+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T00:35:09.490+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T00:35:09.577+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T00:35:09.579+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_order_items, task_id=load_new_order_items, run_id=manual__2025-04-18T00:35:07.408100+00:00, execution_date=20250418T003507, start_date=20250418T003508, end_date=20250418T003509
[2025-04-18T00:35:09.871+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T00:35:09.952+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T00:35:09.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
