[2025-04-18T11:12:58.188+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T11:12:58.271+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-18T11:12:49.599693+00:00 [queued]>
[2025-04-18T11:12:58.288+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-18T11:12:49.599693+00:00 [queued]>
[2025-04-18T11:12:58.290+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T11:12:58.309+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_marts_business> on 2025-04-18 11:12:49.599693+00:00
[2025-04-18T11:12:58.317+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_etl_pipeline_mart', 'dbt_marts_business', 'manual__2025-04-18T11:12:49.599693+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmpjao6xe3c']
[2025-04-18T11:12:58.319+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=373) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T11:12:58.319+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask dbt_marts_business
[2025-04-18T11:12:58.320+0000] {standard_task_runner.py:72} INFO - Started process 375 to run task
[2025-04-18T11:12:58.621+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-18T11:12:49.599693+00:00 [running]> on host f693ba064550
[2025-04-18T11:12:58.920+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='dbt_etl_pipeline_mart' AIRFLOW_CTX_TASK_ID='dbt_marts_business' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T11:12:49.599693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T11:12:49.599693+00:00'
[2025-04-18T11:12:58.921+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T11:12:58.943+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T11:12:58.945+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        export PATH=/home/airflow/.local/bin:$PATH\n        cd /opt/airflow/commerce_dbt\n        dbt run --select marts.business --profiles-dir .\n        ']
[2025-04-18T11:12:58.955+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T11:13:02.348+0000] {subprocess.py:106} INFO - [0m11:13:02  Running with dbt=1.7.0
[2025-04-18T11:13:02.626+0000] {subprocess.py:106} INFO - [0m11:13:02  Registered adapter: postgres=1.7.0
[2025-04-18T11:13:03.198+0000] {subprocess.py:106} INFO - [0m11:13:03  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-18T11:13:03.199+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-04-18T11:13:03.200+0000] {subprocess.py:106} INFO - - seeds.initial_dataset
[2025-04-18T11:13:03.252+0000] {subprocess.py:106} INFO - [0m11:13:03  Found 12 models, 1 snapshot, 6 seeds, 43 tests, 6 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-04-18T11:13:03.256+0000] {subprocess.py:106} INFO - [0m11:13:03
[2025-04-18T11:13:03.984+0000] {subprocess.py:106} INFO - [0m11:13:03  Concurrency: 4 threads (target='dev')
[2025-04-18T11:13:03.986+0000] {subprocess.py:106} INFO - [0m11:13:03
[2025-04-18T11:13:04.010+0000] {subprocess.py:106} INFO - [0m11:13:04  1 of 2 START sql table model commerce_business.customer_orders ................. [RUN]
[2025-04-18T11:13:04.012+0000] {subprocess.py:106} INFO - [0m11:13:04  2 of 2 START sql table model commerce_business.product_sales ................... [RUN]
[2025-04-18T11:13:04.371+0000] {subprocess.py:106} INFO - [0m11:13:04  1 of 2 OK created sql table model commerce_business.customer_orders ............ [[32mSELECT 1000[0m in 0.36s]
[2025-04-18T11:13:04.372+0000] {subprocess.py:106} INFO - [0m11:13:04  2 of 2 OK created sql table model commerce_business.product_sales .............. [[32mSELECT 17[0m in 0.35s]
[2025-04-18T11:13:04.446+0000] {subprocess.py:106} INFO - [0m11:13:04
[2025-04-18T11:13:04.447+0000] {subprocess.py:106} INFO - [0m11:13:04  Finished running 2 table models in 0 hours 0 minutes and 1.19 seconds (1.19s).
[2025-04-18T11:13:04.479+0000] {subprocess.py:106} INFO - [0m11:13:04
[2025-04-18T11:13:04.480+0000] {subprocess.py:106} INFO - [0m11:13:04  [32mCompleted successfully[0m
[2025-04-18T11:13:04.482+0000] {subprocess.py:106} INFO - [0m11:13:04
[2025-04-18T11:13:04.483+0000] {subprocess.py:106} INFO - [0m11:13:04  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-04-18T11:13:05.645+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T11:13:05.821+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T11:13:05.822+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_etl_pipeline_mart, task_id=dbt_marts_business, run_id=manual__2025-04-18T11:12:49.599693+00:00, execution_date=20250418T111249, start_date=20250418T111258, end_date=20250418T111305
[2025-04-18T11:13:05.991+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T11:13:06.179+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T11:13:06.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
