[2025-04-19T16:05:39.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T16:05:39.797+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-19T16:05:27.599196+00:00 [queued]>
[2025-04-19T16:05:39.819+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-19T16:05:27.599196+00:00 [queued]>
[2025-04-19T16:05:39.833+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T16:05:39.855+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_marts_business> on 2025-04-19 16:05:27.599196+00:00
[2025-04-19T16:05:39.863+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6439) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T16:05:39.865+0000] {standard_task_runner.py:72} INFO - Started process 6440 to run task
[2025-04-19T16:05:39.863+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_etl_pipeline_mart', 'dbt_marts_business', 'manual__2025-04-19T16:05:27.599196+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmpaeg5nxmf']
[2025-04-19T16:05:39.866+0000] {standard_task_runner.py:105} INFO - Job 266: Subtask dbt_marts_business
[2025-04-19T16:05:40.189+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business manual__2025-04-19T16:05:27.599196+00:00 [running]> on host 27536697ee14
[2025-04-19T16:05:40.619+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='dbt_etl_pipeline_mart' AIRFLOW_CTX_TASK_ID='dbt_marts_business' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T16:05:27.599196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-19T16:05:27.599196+00:00'
[2025-04-19T16:05:40.620+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T16:05:40.636+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-19T16:05:40.638+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        export PATH=/home/airflow/.local/bin:$PATH\n        cd /opt/airflow/commerce_dbt\n        dbt run --select marts.business --profiles-dir .\n        ']
[2025-04-19T16:05:40.654+0000] {subprocess.py:99} INFO - Output:
[2025-04-19T16:05:43.314+0000] {subprocess.py:106} INFO - [0m16:05:43  Running with dbt=1.7.0
[2025-04-19T16:05:43.594+0000] {subprocess.py:106} INFO - [0m16:05:43  Registered adapter: postgres=1.7.0
[2025-04-19T16:05:43.936+0000] {subprocess.py:106} INFO - [0m16:05:43  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-19T16:05:43.936+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-04-19T16:05:43.937+0000] {subprocess.py:106} INFO - - seeds.initial_dataset
[2025-04-19T16:05:44.038+0000] {subprocess.py:106} INFO - [0m16:05:44  Found 13 models, 1 snapshot, 6 seeds, 43 tests, 6 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-04-19T16:05:44.042+0000] {subprocess.py:106} INFO - [0m16:05:44
[2025-04-19T16:05:44.531+0000] {subprocess.py:106} INFO - [0m16:05:44  Concurrency: 4 threads (target='dev')
[2025-04-19T16:05:44.532+0000] {subprocess.py:106} INFO - [0m16:05:44
[2025-04-19T16:05:44.543+0000] {subprocess.py:106} INFO - [0m16:05:44  1 of 2 START sql table model commerce_business.customer_orders ................. [RUN]
[2025-04-19T16:05:44.544+0000] {subprocess.py:106} INFO - [0m16:05:44  2 of 2 START sql table model commerce_business.product_sales ................... [RUN]
[2025-04-19T16:05:44.836+0000] {subprocess.py:106} INFO - [0m16:05:44  1 of 2 OK created sql table model commerce_business.customer_orders ............ [[32mSELECT 1000[0m in 0.29s]
[2025-04-19T16:05:44.839+0000] {subprocess.py:106} INFO - [0m16:05:44  2 of 2 OK created sql table model commerce_business.product_sales .............. [[32mSELECT 17[0m in 0.29s]
[2025-04-19T16:05:44.912+0000] {subprocess.py:106} INFO - [0m16:05:44
[2025-04-19T16:05:44.913+0000] {subprocess.py:106} INFO - [0m16:05:44  Finished running 2 table models in 0 hours 0 minutes and 0.87 seconds (0.87s).
[2025-04-19T16:05:44.951+0000] {subprocess.py:106} INFO - [0m16:05:44
[2025-04-19T16:05:44.952+0000] {subprocess.py:106} INFO - [0m16:05:44  [32mCompleted successfully[0m
[2025-04-19T16:05:44.953+0000] {subprocess.py:106} INFO - [0m16:05:44
[2025-04-19T16:05:44.955+0000] {subprocess.py:106} INFO - [0m16:05:44  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-04-19T16:05:45.818+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-19T16:05:45.959+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T16:05:45.961+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_etl_pipeline_mart, task_id=dbt_marts_business, run_id=manual__2025-04-19T16:05:27.599196+00:00, execution_date=20250419T160527, start_date=20250419T160539, end_date=20250419T160545
[2025-04-19T16:05:46.147+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T16:05:46.216+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T16:05:46.220+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
